# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.models.regulations_response_regulations_info_inner import RegulationsResponseRegulationsInfoInner

class TestRegulationsResponseRegulationsInfoInner(unittest.TestCase):
    """RegulationsResponseRegulationsInfoInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegulationsResponseRegulationsInfoInner:
        """Test RegulationsResponseRegulationsInfoInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegulationsResponseRegulationsInfoInner`
        """
        model = RegulationsResponseRegulationsInfoInner()
        if include_optional:
            return RegulationsResponseRegulationsInfoInner(
                exchange = 56,
                product = 56,
                side = '',
                reason = '',
                limit_start_day = '',
                limit_end_day = '',
                level = 56
            )
        else:
            return RegulationsResponseRegulationsInfoInner(
        )
        """

    def testRegulationsResponseRegulationsInfoInner(self):
        """Test RegulationsResponseRegulationsInfoInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
