# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.models.wallet_future_success import WalletFutureSuccess

class TestWalletFutureSuccess(unittest.TestCase):
    """WalletFutureSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletFutureSuccess:
        """Test WalletFutureSuccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletFutureSuccess`
        """
        model = WalletFutureSuccess()
        if include_optional:
            return WalletFutureSuccess(
                future_trade_limit = 1.337,
                margin_requirement = 1.337,
                margin_requirement_sell = 1.337
            )
        else:
            return WalletFutureSuccess(
        )
        """

    def testWalletFutureSuccess(self):
        """Test WalletFutureSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
