# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.api.order_api import OrderApi


class TestOrderApi(unittest.TestCase):
    """OrderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrderApi()

    def tearDown(self) -> None:
        pass

    def test_cancelorder_put(self) -> None:
        """Test case for cancelorder_put

        注文取消
        """
        pass

    def test_sendoder_future_post(self) -> None:
        """Test case for sendoder_future_post

        注文発注（先物）
        """
        pass

    def test_sendorder_option_post(self) -> None:
        """Test case for sendorder_option_post

        注文発注（オプション）
        """
        pass

    def test_sendorder_post(self) -> None:
        """Test case for sendorder_post

        注文発注（現物・信用）
        """
        pass


if __name__ == '__main__':
    unittest.main()
