# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.models.positions_success import PositionsSuccess

class TestPositionsSuccess(unittest.TestCase):
    """PositionsSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PositionsSuccess:
        """Test PositionsSuccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PositionsSuccess`
        """
        model = PositionsSuccess()
        if include_optional:
            return PositionsSuccess(
                execution_id = '',
                account_type = 56,
                symbol = '',
                symbol_name = '',
                exchange = 56,
                exchange_name = '',
                security_type = 56,
                execution_day = 56,
                price = 1.337,
                leaves_qty = 1.337,
                hold_qty = 1.337,
                side = '',
                expenses = 1.337,
                commission = 1.337,
                commission_tax = 1.337,
                expire_day = 56,
                margin_trade_type = 56,
                current_price = 1.337,
                valuation = 1.337,
                profit_loss = 1.337,
                profit_loss_rate = 1.337
            )
        else:
            return PositionsSuccess(
        )
        """

    def testPositionsSuccess(self):
        """Test PositionsSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
