# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.models.api_soft_limit_response import ApiSoftLimitResponse

class TestApiSoftLimitResponse(unittest.TestCase):
    """ApiSoftLimitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiSoftLimitResponse:
        """Test ApiSoftLimitResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiSoftLimitResponse`
        """
        model = ApiSoftLimitResponse()
        if include_optional:
            return ApiSoftLimitResponse(
                stock = 1.337,
                margin = 1.337,
                future = 1.337,
                future_mini = 1.337,
                future_micro = 1.337,
                option = 1.337,
                mini_option = 1.337,
                kabu_s_version = ''
            )
        else:
            return ApiSoftLimitResponse(
        )
        """

    def testApiSoftLimitResponse(self):
        """Test ApiSoftLimitResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
