# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.models.ranking_by_margin_response_ranking_inner import RankingByMarginResponseRankingInner

class TestRankingByMarginResponseRankingInner(unittest.TestCase):
    """RankingByMarginResponseRankingInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RankingByMarginResponseRankingInner:
        """Test RankingByMarginResponseRankingInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RankingByMarginResponseRankingInner`
        """
        model = RankingByMarginResponseRankingInner()
        if include_optional:
            return RankingByMarginResponseRankingInner(
                var_false = 56,
                symbol = '',
                symbol_name = '',
                sell_rapid_payment_percentage = 1.337,
                sell_last_week_ratio = 1.337,
                buy_rapid_payment_percentage = 1.337,
                buy_last_week_ratio = 1.337,
                ratio = 1.337,
                exchange_name = '',
                category_name = ''
            )
        else:
            return RankingByMarginResponseRankingInner(
        )
        """

    def testRankingByMarginResponseRankingInner(self):
        """Test RankingByMarginResponseRankingInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
