# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.models.symbol_success import SymbolSuccess

class TestSymbolSuccess(unittest.TestCase):
    """SymbolSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SymbolSuccess:
        """Test SymbolSuccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SymbolSuccess`
        """
        model = SymbolSuccess()
        if include_optional:
            return SymbolSuccess(
                symbol = '',
                symbol_name = '',
                display_name = '',
                exchange = 56,
                exchange_name = '',
                bis_category = '',
                total_market_value = 1.337,
                total_stocks = 1.337,
                trading_unit = 1.337,
                fiscal_year_end_basic = 56,
                price_range_group = '',
                kc_margin_buy = True,
                kc_margin_sell = True,
                margin_buy = True,
                margin_sell = True,
                upper_limit = 1.337,
                lower_limit = 1.337,
                underlyer = '',
                deriv_month = '',
                trade_start = 56,
                trade_end = 56,
                strike_price = 1.337,
                put_or_call = 56,
                clearing_price = 1.337
            )
        else:
            return SymbolSuccess(
        )
        """

    def testSymbolSuccess(self):
        """Test SymbolSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
