# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.models.request_send_order_deriv_future import RequestSendOrderDerivFuture

class TestRequestSendOrderDerivFuture(unittest.TestCase):
    """RequestSendOrderDerivFuture unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestSendOrderDerivFuture:
        """Test RequestSendOrderDerivFuture
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestSendOrderDerivFuture`
        """
        model = RequestSendOrderDerivFuture()
        if include_optional:
            return RequestSendOrderDerivFuture(
                password = 'xxxxxx',
                symbol = '165120019',
                exchange = 56,
                trade_type = 56,
                time_in_force = 56,
                side = '',
                qty = 56,
                close_position_order = 56,
                close_positions = [
                    kabustation_client.models.positions_deriv.PositionsDeriv(
                        hold_id = '', 
                        qty = 56, )
                    ],
                front_order_type = 56,
                price = 1.337,
                expire_day = 56,
                reverse_limit_order = kabustation_client.models.request_send_order_deriv_future_reverse_limit_order.RequestSendOrderDerivFuture_ReverseLimitOrder(
                    trigger_price = 1.337, 
                    under_over = 56, 
                    after_hit_order_type = 56, 
                    after_hit_price = 1.337, )
            )
        else:
            return RequestSendOrderDerivFuture(
                password = 'xxxxxx',
                symbol = '165120019',
                exchange = 56,
                trade_type = 56,
                time_in_force = 56,
                side = '',
                qty = 56,
                front_order_type = 56,
                price = 1.337,
                expire_day = 56,
        )
        """

    def testRequestSendOrderDerivFuture(self):
        """Test RequestSendOrderDerivFuture"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
