# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.api.wallet_api import WalletApi


class TestWalletApi(unittest.TestCase):
    """WalletApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WalletApi()

    def tearDown(self) -> None:
        pass

    def test_wallet_cash_get(self) -> None:
        """Test case for wallet_cash_get

        取引余力（現物）
        """
        pass

    def test_wallet_cash_symbol_get(self) -> None:
        """Test case for wallet_cash_symbol_get

        取引余力（現物）（銘柄指定）
        """
        pass

    def test_wallet_future_get(self) -> None:
        """Test case for wallet_future_get

        取引余力（先物）
        """
        pass

    def test_wallet_future_symbol_get(self) -> None:
        """Test case for wallet_future_symbol_get

        取引余力（先物）（銘柄指定）
        """
        pass

    def test_wallet_margin_get(self) -> None:
        """Test case for wallet_margin_get

        取引余力（信用）
        """
        pass

    def test_wallet_margin_symbol_get(self) -> None:
        """Test case for wallet_margin_symbol_get

        取引余力（信用）（銘柄指定）
        """
        pass

    def test_wallet_option_get(self) -> None:
        """Test case for wallet_option_get

        取引余力（オプション）
        """
        pass

    def test_wallet_option_symbol_get(self) -> None:
        """Test case for wallet_option_symbol_get

        取引余力（オプション）（銘柄指定）
        """
        pass


if __name__ == '__main__':
    unittest.main()
