# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.api.info_api import InfoApi


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InfoApi()

    def tearDown(self) -> None:
        pass

    def test_apisoftlimit_get(self) -> None:
        """Test case for apisoftlimit_get

        ソフトリミット
        """
        pass

    def test_board_get(self) -> None:
        """Test case for board_get

        時価情報・板情報
        """
        pass

    def test_exchange_get(self) -> None:
        """Test case for exchange_get

        為替情報
        """
        pass

    def test_marginpremium_get(self) -> None:
        """Test case for marginpremium_get

        プレミアム料取得
        """
        pass

    def test_orders_get(self) -> None:
        """Test case for orders_get

        注文約定照会
        """
        pass

    def test_positions_get(self) -> None:
        """Test case for positions_get

        残高照会
        """
        pass

    def test_primary_exchange_get(self) -> None:
        """Test case for primary_exchange_get

        優先市場
        """
        pass

    def test_ranking_get(self) -> None:
        """Test case for ranking_get

        詳細ランキング
        """
        pass

    def test_regulations_get(self) -> None:
        """Test case for regulations_get

        規制情報
        """
        pass

    def test_symbol_get(self) -> None:
        """Test case for symbol_get

        銘柄情報
        """
        pass

    def test_symbolname_future_get(self) -> None:
        """Test case for symbolname_future_get

        先物銘柄コード取得
        """
        pass

    def test_symbolname_option_get(self) -> None:
        """Test case for symbolname_option_get

        オプション銘柄コード取得
        """
        pass

    def test_symbolname_option_mini_get(self) -> None:
        """Test case for symbolname_option_mini_get

        ミニオプション（限週）銘柄コード取得
        """
        pass


if __name__ == '__main__':
    unittest.main()
