# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.models.wallet_margin_success import WalletMarginSuccess

class TestWalletMarginSuccess(unittest.TestCase):
    """WalletMarginSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletMarginSuccess:
        """Test WalletMarginSuccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletMarginSuccess`
        """
        model = WalletMarginSuccess()
        if include_optional:
            return WalletMarginSuccess(
                margin_account_wallet = 1.337,
                depositkeep_rate = 1.337,
                consignment_deposit_rate = 1.337,
                cash_of_consignment_deposit_rate = 1.337
            )
        else:
            return WalletMarginSuccess(
        )
        """

    def testWalletMarginSuccess(self):
        """Test WalletMarginSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
