# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kabustation_client.models.request_send_order import RequestSendOrder

class TestRequestSendOrder(unittest.TestCase):
    """RequestSendOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestSendOrder:
        """Test RequestSendOrder
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestSendOrder`
        """
        model = RequestSendOrder()
        if include_optional:
            return RequestSendOrder(
                password = '',
                symbol = '',
                exchange = 56,
                security_type = 56,
                side = '',
                cash_margin = 56,
                margin_trade_type = 56,
                margin_premium_unit = 1.337,
                deliv_type = 56,
                fund_type = '',
                account_type = 56,
                qty = 56,
                close_position_order = 56,
                close_positions = [
                    kabustation_client.models.positions.Positions(
                        hold_id = '', 
                        qty = 56, )
                    ],
                front_order_type = 56,
                price = 1.337,
                expire_day = 56,
                reverse_limit_order = kabustation_client.models.request_send_order_reverse_limit_order.RequestSendOrder_ReverseLimitOrder(
                    trigger_sec = 56, 
                    trigger_price = 1.337, 
                    under_over = 56, 
                    after_hit_order_type = 56, 
                    after_hit_price = 1.337, )
            )
        else:
            return RequestSendOrder(
                password = '',
                symbol = '',
                exchange = 56,
                security_type = 56,
                side = '',
                cash_margin = 56,
                deliv_type = 56,
                account_type = 56,
                qty = 56,
                front_order_type = 56,
                price = 1.337,
                expire_day = 56,
        )
        """

    def testRequestSendOrder(self):
        """Test RequestSendOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
