# coding: utf-8

"""
    kabuステーションAPI

    # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)

    The version of the OpenAPI document: 1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class WalletMarginSuccess(BaseModel):
    """
    WalletMarginSuccess
    """ # noqa: E501
    margin_account_wallet: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="信用新規可能額", alias="MarginAccountWallet")
    depositkeep_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="保証金維持率<br>※銘柄指定の場合のみ<br>※銘柄が指定されなかった場合、0.0を返す。", alias="DepositkeepRate")
    consignment_deposit_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="委託保証金率<br>※銘柄指定の場合のみ。<br>※銘柄が指定されなかった場合、Noneを返す。", alias="ConsignmentDepositRate")
    cash_of_consignment_deposit_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="現金委託保証金率<br>※銘柄指定の場合のみ。<br>※銘柄が指定されなかった場合、Noneを返す。", alias="CashOfConsignmentDepositRate")
    __properties: ClassVar[List[str]] = ["MarginAccountWallet", "DepositkeepRate", "ConsignmentDepositRate", "CashOfConsignmentDepositRate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WalletMarginSuccess from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WalletMarginSuccess from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "MarginAccountWallet": obj.get("MarginAccountWallet"),
            "DepositkeepRate": obj.get("DepositkeepRate"),
            "ConsignmentDepositRate": obj.get("ConsignmentDepositRate"),
            "CashOfConsignmentDepositRate": obj.get("CashOfConsignmentDepositRate")
        })
        return _obj


